matrix:
  - name: markdown
    sources:
      - 'content/**/*.md'
    aspell:
      lang: en
      ignore-case: true
    dictionary:
      wordlists:
        - .pyspelling.wordlist
    pipeline:
      - pyspelling.filters.markdown:
          markdown_extensions:
            - markdown.extensions.fenced_code
            - markdown.extensions.attr_list
      - pyspelling.filters.html:
          comments: false
          attributes:
            - alt
            - title
          ignores:
            - code
            - pre
            - nospell
