[project]
name = "cecinestpasun"
version = "0.1.0"
description = "Personal blog of Russell Keith-Magee"
readme = "README.md"
requires-python = "~=3.14.0"
dependencies = [
    "pelican == 4.12.0",
    "markdown==3.10.3",
    "pygments==2.20.0",
    "typogrify == 2.1.0",
    "pytz == 2026.3.post1",
]
